import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container } from "./components/Container/Container";
import { Header } from "./components/Header/Header";
import { AuthProvider } from "@/providers/AuthProvider";
import { Main } from "./components/Main/Main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <Container>
            <Header />
            <Main>{children}</Main>
          </Container>
        </AuthProvider>
      </body>
    </html>
  );
}
